name: Docker Build

on:
  push:
    branches: [ develop ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/python.Dockerfile
          push: false
          tags: autoops-sentinel/api:ci
      - name: Build Frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/frontend.Dockerfile
          push: false
          tags: autoops-sentinel/frontend:ci


